# .github/workflows/manage-startup.yml
name: Manage Startup Apps
on: workflow_dispatch
jobs:
  audit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Startup Apps
        shell: pwsh
        run: .\.github\workflows\Manage-StartupApps.ps1
